sandbox-roberto-safari-tests
m-lab/ndt7-js pull request #45
Opened 2021-05-14 16:02 UTC by robertodauria

This works around the Safari bug where bufferedAmount isn't updated immediately after a send() and thus causes the while() loop to spin extremely fast at the beginning of the test (when messages are small).

This causes the code to crash because we're trying to send more data than the WS buffer can handle.

2021-05-14 17:12 UTC, stephen-soltesz requested changes
> Reviewed 3 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/m-lab/ndt7-js/45)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @robertodauria)

___
*[src/ndt7-upload-worker.js, line 61 at r1](https://reviewable.io/reviews/m-lab/ndt7-js/45#-M_fmZO1CmaKOnG975Tw:-M_fmZO1CmaKOnG975Tx:b-8enij1) ([raw file](https://github.com/m-lab/ndt7-js/blob/05cf60b10299fd86b629f41cf4ad13ca78f68924/src/ndt7-upload-worker.js#L61)):*
> ```
>    * time and maintain the invariant that the message size is always either 8k
>    * or less than 1/8 of the total number of bytes we have enqueued. In an
> ```

Is this still accurate?
___
*[src/ndt7-upload-worker.js, line 88 at r1](https://reviewable.io/reviews/m-lab/ndt7-js/45#-M_fmBOq57D9drBGJpGV:-M_fmAW92XkuNdzNIIOS:b-8u7byv) ([raw file](https://github.com/m-lab/ndt7-js/blob/05cf60b10299fd86b629f41cf4ad13ca78f68924/src/ndt7-upload-worker.js#L88)):*
> ```JavaScript
>     // Message size is doubled every 16 messages, up to maxMessageSize.
>     if (data.length < maxMessageSize &&
>       data.length < (total - sock.bufferedAmount) / 16) {
> ```

I find this logic difficult to follow.

`total` includes all earlier data lengths, right?

The original logic (also a little hard to follow) made a strict threshold for "nextSizeIncrement" independent of total.

Model of current logic in Python (assuming bufferedAmount == 0).

```
b = 8192                                                                        
maxMessageSize = 8388608 # /* = (1<<23) = 8MB */                                
total = 0                                                                       
i = 0                                                                           
                                                                                
while i < 100:                                                                  
    i+=1                                                                        
    if (b < maxMessageSize and b < (total) / 16):                               
        b = b*2                                                                 
    print(i, b, total, total/16)                                                
    total += b    
```


<!-- Sent from Reviewable.io -->

2021-05-14 20:41 UTC, robertodauria reviewed
> *[Reviewable](https://reviewable.io/reviews/m-lab/ndt7-js/45)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[src/ndt7-upload-worker.js, line 61 at r1](https://reviewable.io/reviews/m-lab/ndt7-js/45#-M_fmZO1CmaKOnG975Tw:-M_gVgXn6c1_YqZDBZeE:blhggf8) ([raw file](https://github.com/m-lab/ndt7-js/blob/05cf60b10299fd86b629f41cf4ad13ca78f68924/src/ndt7-upload-worker.js#L61)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

> ```
>    * time and maintain the invariant that the message size is always either 8k
>    * or less than 1/8 of the total number of bytes we have enqueued. In an
> ```

Is this still accurate?
</blockquote></details>

I think it's still accurate unless the JS event loop can't keep up with the network -- but that was true for the previous code, too.
___
*[src/ndt7-upload-worker.js, line 88 at r1](https://reviewable.io/reviews/m-lab/ndt7-js/45#-M_fmBOq57D9drBGJpGV:-M_gVmCn0UmN1KYlPTn5:b-tbt4i9) ([raw file](https://github.com/m-lab/ndt7-js/blob/05cf60b10299fd86b629f41cf4ad13ca78f68924/src/ndt7-upload-worker.js#L88)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

I find this logic difficult to follow.

`total` includes all earlier data lengths, right?

The original logic (also a little hard to follow) made a strict threshold for "nextSizeIncrement" independent of total.

Model of current logic in Python (assuming bufferedAmount == 0).

```
b = 8192                                                                        
maxMessageSize = 8388608 # /* = (1<<23) = 8MB */                                
total = 0                                                                       
i = 0                                                                           
                                                                                
while i < 100:                                                                  
    i+=1                                                                        
    if (b < maxMessageSize and b < (total) / 16):                               
        b = b*2                                                                 
    print(i, b, total, total/16)                                                
    total += b    
```
</blockquote></details>

I've changed it to pre-calculate `nextSizeIncrement`. As discussed on Slack/VC, I also think it's a good idea to consider `bufferedAmount` here (the previous code didn't). If the network isn't fast enough to transfer the buffer's content, we don't want to keep doubling the message size. `(total - sock.bufferedAmount)` tells us how much data has been actually sent through the network (vs how much data has been queued)


<!-- Sent from Reviewable.io -->

2021-05-14 21:55 UTC, stephen-soltesz approved these changes
> *[Reviewable](https://reviewable.io/reviews/m-lab/ndt7-js/45)* status: :shipit: complete! 1 of 1 approvals obtained

___
*[src/ndt7-upload-worker.js, line 88 at r1](https://reviewable.io/reviews/m-lab/ndt7-js/45#-M_fmBOq57D9drBGJpGV:-M_grt-rElVhg9M6drvB:b-9755fn) ([raw file](https://github.com/m-lab/ndt7-js/blob/05cf60b10299fd86b629f41cf4ad13ca78f68924/src/ndt7-upload-worker.js#L88)):*
<details><summary><i>Previously, robertodauria (Roberto D'Auria) wrote…</i></summary><blockquote>

I've changed it to pre-calculate `nextSizeIncrement`. As discussed on Slack/VC, I also think it's a good idea to consider `bufferedAmount` here (the previous code didn't). If the network isn't fast enough to transfer the buffer's content, we don't want to keep doubling the message size. `(total - sock.bufferedAmount)` tells us how much data has been actually sent through the network (vs how much data has been queued)
</blockquote></details>

Thank you!


<!-- Sent from Reviewable.io -->

2021-05-14 21:58 UTC, merged

2021-05-17 17:15 UTC, RA80533 commented
Is the slack open to contributors outside of the organization?

2021-05-17 19:35 UTC, laiyi-ohlsen commented
Hi @RA80533, definitely. Thank you for submitting the PRs you have. We're working on refining our process for reviewing external contributions outside of the core contributors team, but in the mean time, if you're interested in contributing more, could you reach out to me at laiyi@measurementlab.net? Thanks!